version: '3.4'

services:
  testidempotentapi:
    image: ${DOCKER_REGISTRY-}testidempotentapi
    build:
      context: .
      dockerfile: IdempotentApi/Dockerfile

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local